language: generic
addons:
  apt:
    packages:
      - python2.7
      - python3
      - tox
script:
  # 'hpcugent' is a mandatory remote for setup.py to work (because of get_name_url)
  - git remote add hpcugent https://github.com/hpcugent/vsc-install.git
  - tox -v
